Add spect
microjs/microjs.com pull request #1035
Opened 2020-05-31 19:07 UTC by dy

4.4kb framework - includes full-featured hyperscript support, observables and selector-based aspects.
https://github.com/spectjs/spect

2020-08-19 01:46 UTC, dy commented
Hallou?

2021-04-24 16:20 UTC, dy commented
Ping

2021-04-26 16:36 UTC, pineapplemachine requested changes

2021-04-26 16:36 UTC, pineapplemachine commented on data.js
> +    source: "https://unpkg.com/browse/spect@22.0.0/dist/spect.min.js"
This should be a link to raw and unminified source code. Please refer to the repository's readme, which lays out what is expected of submitted packages.

> The 'source' attribute must point to a single-file, or an array of files that can be concatenated to form your complete library in a ready-to-use form. The 'source' must not be minified

2021-04-26 16:38 UTC, pineapplemachine commented on data.js
> +    source: "https://unpkg.com/browse/spect@22.0.0/dist/spect.min.js"
Sorry for the delay. I've been pretty absorbed with other things. Unfortunately I don't think there's anyone very actively maintaining this repository at the moment.

2022-08-15 11:02 UTC, merged